kind: lab/v1
name: kube-goat
tags:
- preview
- official

boxes:
- template: box/base/ubuntu

infra:
- alias: kube-goat-home
  source: helm
  repositoryUrl: https://github.com/madhuakula/kubernetes-goat.git
  targetRevision: master
  path: kubernetes-goat/scenarios/kubernetes-goat-home
