kind: lab/v1
name: vulhub-gitlab
tags:
- preview
- official

boxes:
- template: box/base/ubuntu

infra:
- alias: CVE-2016-9086
  source: compose
  repositoryUrl: https://github.com/vulhub/vulhub.git
  targetRevision: master
  path: gitlab/CVE-2016-9086
