---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "application.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "application.labels" . | nindent 8 }}
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      # main
      - name: {{ include "application.repository" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        tty: true
        stdin: true
        # ports
        {{- with .Values.ports }}
        ports:
        {{- range $key, $value := . }}
        - name: {{ $key }}-svc
          containerPort: {{ $value.port }}
          protocol: TCP
        {{- end }}
        {{- end }}
        # env
        {{- with .Values.env }}
        env:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        # resources
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      # sidecar vpn
      {{- if .Values.vpn.enabled }}
      - name: "sidecar-vpn"
        image: "{{ .Values.vpn.image.repository }}:{{ .Values.vpn.image.version }}"
        imagePullPolicy: {{ .Values.vpn.image.pullPolicy }}
        env:
        - name: OPENVPN_CONFIG
          value: "{{ .Values.vpn.secret.basePath }}/{{ .Values.vpn.secret.path }}"
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        volumeMounts:
        - name: tun-device-volume
          mountPath: /dev/net/tun
          readOnly: true
        - name: {{ .Values.vpn.secret.volumeName }}
          mountPath: {{ .Values.vpn.secret.basePath }}
          readOnly: true
      {{- end }}
      # volumes
      {{- if .Values.vpn.enabled }}
      volumes:
      {{- if .Values.vpn.enabled }}
      - name: tun-device-volume
        hostPath:
          path: /dev/net/tun
      {{- end }}
      {{- if .Values.vpn.secret.create }}
      - name: {{ .Values.vpn.secret.volumeName }}
        secret:
          secretName: {{ include "application.fullname" . }}-sidecar-vpn-secret
          items:
          - key: openvpn-config
            path: {{ .Values.vpn.secret.path }}
      {{- end }}
      {{- end }}
