{{- if .Values.ports }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "application.labels" . | nindent 4 }}
  type: ClusterIP
  ports:
  {{- range $key, $value := .Values.ports }}
  - name: {{ $key }}
    protocol: TCP
    port: {{ $value.port }}
    targetPort: {{ $key }}-svc
  {{- end }}
{{- end }}
