# e.g. "hckops"
namespace: INVALID_NAMESPACE
# e.g. "box" without dash
namePrefix: ""
# nameOverride has precedence over namePrefix
nameOverride: ""
# name without version suffix
fullnameOverride: ""

image:
  repository: INVALID_ORG/NAME
  version: latest
  pullPolicy: Always

env: []
  # - name: PASSWORD
  #   value: "changeme"

resources: {}
  # requests:
  #   memory: 512Mi
  #   cpu: 500m
  # limits:
  #   memory: 512Mi

ports: {}
  # vnc:
  #   port: 5900
  # novnc:
  #   port: 6080
  # tty:
  #   port: 7681
