name: docker-ci

on:
  # enable manual trigger
  workflow_dispatch:
  schedule:
    # every 24 hours at midnight
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker-*.yml'
      - 'docker/**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  DOCKER_REPOSITORY: hckops

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    # makes sure it doesn't finish the minutes quota if stalls
    timeout-minutes: 30

    # alternative to loop: parallel builds
    strategy:
      matrix:
        images:
          - path: boxes
            name: box-alpine
          - path: boxes
            name: box-parrot
          - path: boxes
            name: box-todo

    steps:
      - name: Output Test
        run: echo "${{ matrix.images.path }}/${{ matrix.images.name }}"
