name: docker-ci

on:
  # enable manual trigger
  workflow_dispatch:
  schedule:
    # every 24 hours at midnight
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker-*.yml'
      - 'docker/**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  DOCKER_REPOSITORY: hckops

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    # makes sure it doesn't finish the minutes quota if stalls
    timeout-minutes: 30

    # alternative to loop: parallel builds
    strategy:
      matrix:
        images:
          - path: boxes
            name: box-alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Docker CI
        uses: hckops/actions/docker-template-action@main
        with:
          DOCKER_CONTEXT: ./docker/${{ matrix.images.path }}/${{ matrix.images.name }}
          DOCKER_IMAGE_NAME: ${{ matrix.images.name }}
          DOCKER_REPOSITORY: ${{ env.DOCKER_REPOSITORY }}
          # repository secrets
          SECRET_DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          SECRET_DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          SECRET_DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
