name: helm-ci

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/helm-ci.yml'
      - 'charts/**'

jobs:
  helm-lint:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Helm Lint
        uses: hckops/actions/helm-lint-action@v0.11.0

  helm-release:
    # release depends on lint
    needs: helm-lint

    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "hckbot"
          git config user.email "hckbot@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
